### ISSUE TITLE
Uploading to docker reigstry/Send PR?

### ISSUE THREAD

**Issue by saketkc** [doug/linuxbrew-standalone#1]
Hi ,

Do you plan to upload this to docker registry? @sjackman also maintains similar repos:
https://github.com/sjackman/docker-linuxbrew

It might make sense to keep this in-sync.

**Comment by sjackman** [comment]
See https://github.com/sjackman/docker-linuxbrew/tree/master/linuxbrew-standalone
and https://registry.hub.docker.com/u/sjackman/linuxbrew-standalone/

**Comment by doug** [comment]
Awesome, unless there is an objection will go ahead and delete this repo, one less thing to maintain :) wish I had known about your project before hand. Thanks @sjackman and @saketkc

**Comment by doug** [comment]
One thing that would be nice on your repo @sjackman would be a release on github of the standalone binaries for x86_64 that I can just curl tar onto a machine I don't have root too.  Like I did here: https://github.com/doug/linuxbrew-standalone/releases. Would you be open to adding that?
